### ISSUE TITLE
run the demo failed

### ISSUE THREAD

**Issue by arohamirai** [acschaefer/ple#1]
Hi:
i run your code in MATLAB R2013b following  Quick Start Instructions part, but failed, there some error below：
1.  Undefined function 'startsWith' for input arguments of type 'char'.
2. Undefined function 'angdiff' for input arguments of type 'double'.
3. Error using  +,  Matrix dimensions must agree in  obj.enddata = obj.spdata(:,1:2) + [x,y];

i guess there some toolboxs i have not installed, and after search google, i tried to fix the errors, my  solution:
fix error 1:  
change startsWith(line, 'str')   to javaMethod('startsWith',java.lang.String(line), 'str')   and  startsWith(line, {'str1', 'str2'})  to  javaMethod('startsWith',java.lang.String(line), 'str2')  ||  javaMethod('startsWith',java.lang.String(line), 'str2') 

fix error2 :
 it seems the function is in Robotics Toolbox for MATLAB, but i am not sure.  but i install it, and seems fixed,

fix error3:
Honestly i didn't fix it.

so it will be appreciate if you can  figure out what toolbox does this project depends on, hope you reply. thanks

**Comment by ixgn** [comment]
Hi, thanks for reporting these issues.
> Undefined function 'startsWith' for input arguments of type 'char'.

This was introduced in [MATLAB R2016b](https://www.mathworks.com/help/matlab/ref/startswith.html).
> Undefined function 'angdiff' for input arguments of type 'double'.

Right, this needs the robotics toolbox. I've added a comment to the README.
> Error using +, Matrix dimensions must agree in obj.enddata = obj.spdata(:,1:2) + [x,y];

I would guess this is caused by your old MATLAB version. Can you run in a newer MATLAB version? We tested R2017b and R2018a.

**Comment by arohamirai** [comment]
Thank you for reply, i update MATLAB to R2018a  and installed  the robotics toolbox, then the demo run succeed.
