### ISSUE TITLE
carmenread error on Matlab2019

### ISSUE THREAD

**Issue by aaravrav142** [acschaefer/ple#2]
Hi, 

I am trying to use your program on Matlab 2019a with robotics toolbox. However when running `extrlin` command, I am getting:
```
Error using carmenread (line 56)
File '..\data\carmen\belgioioso-corrected.log.gz' does not exist.
Error in extrlin (line 6)
[~,ls] = carmenread(datafile);
```
I can see the data in the carmen folder but do not understand why it can't be read. Can you help me with this? 
Thanks

**Comment by acschaefer** [comment]
Maybe this error has nothing to do with the `carmenread` function. To debug this issue, I would double check the working directory using Matlab's built-in `pwd` function. Does `<working directory>/../data/carmen/belgioioso-corrected.log.gz` really exist?

**Comment by aaravrav142** [comment]
Hi,
Explicitly specifying the file path solved the problem. Though it should have picked up the path automatically. Will figure out later what might be the problem. Perhaps a reinstall of Matlab can solve the problem. Thanks. Closing.
